/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Title: rc4example.cpp
 * Author: Simon Campbell, <simonhmcampbell@gmai.com>
 * Description: Example to provide assemly for inspection
 * License: GPL
 * Date: May 2015
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


#include "RC4Stream.cpp"

using namespace std;

int main(int argc, const char *argv[])
{
   
   //assign space for the key;
   RC4Stream::Key key;

   uint8_t keys[RC4Stream::Key::KEY_LENGTH] = 
                          { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F};

   //Target first 16 btes of output generated by the openssl rc4 command line tool for the keys above
   uint8_t targets[RC4Stream::Key::KEY_LENGTH] = 
                          { 0xe9, 0x9c, 0x40, 0xf9, 0x47, 0xe2, 0x19, 0xcc, 0x06, 0xdb, 0x97, 0xc6, 0x0e, 0xdd, 0x2a, 0x4f };
   //allocate space for the RC4 stream
   RC4Stream rc4Stream;

   
      for(int j = 0; j < RC4Stream::Key::KEY_LENGTH; j++) {
         key.setModuloLength(j, keys[j]);
      }
     //schedule key
     rc4Stream.keySchedule(key);
      
     //run RC4 stream algorithm and collect output in histogram counters
     for (int j = 0; j < RC4Stream::Key::KEY_LENGTH; j++) {
        if(targets[j] != rc4Stream.PRGRound()){
            return 1;
        }
     }

   //close the file and return
   return 0;
}

